version: "3"
services:
  client:
    image: client-image
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - frontend
      - backend

  api:
    image: api-image
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    command: mongod
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data:


networks:
  frontend:
  backend:
